(add-to-list 'load-path' "~/.emacs.d/module/redspace")
(add-to-list 'load-path' "~/.emacs.d/module/auto-java-complete")
(add-to-list 'load-path' "~/.emacs.d/module/jdee/jdee-2.4.1/lisp")
(add-to-list 'load-path' "~/.emacs.d/module/ido-custom")
(add-to-list 'load-path' "~/.emacs.d/module/ggtags")
(provide 'module)
