(global-set-key (kbd "M-]") 'next-buffer)
(global-set-key (kbd "M-[") 'previous-buffer)
(global-set-key (kbd "C-c m") 'set-mark-command)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-c g") 'goto-line)
(global-set-key (kbd "C-c n") 'temp-buffer)
(global-set-key (kbd "C-;") 'switch-to-previous-buffer)
(global-set-key (kbd "C-c f") 'indent-region)

(provide 'key-common)
