(global-set-key (kbd "M-]") 'next-buffer)
(global-set-key (kbd "M-[") 'previous-buffer)
(global-set-key (kbd "C-c m") 'set-mark-command)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-c g") 'goto-line)
(global-set-key (kbd "C-c n") 'temp-buffer)
(global-set-key (kbd "C-;") 'switch-to-previous-buffer)
(global-set-key (kbd "C-c f") 'indent-region)
(global-set-key (kbd "C-c c") 'comment-region)
(global-set-key (kbd "C-c u") 'uncomment-region)
(global-set-key (kbd "C-M-[")  'windmove-left)
(global-set-key (kbd "C-M-]") 'windmove-right)
(global-set-key (kbd "C-M-=")    'windmove-up)
(global-set-key (kbd "C-M-'")  'windmove-down)
(provide 'key-common)
