;;feature list

(require 'elpa-configure)
(require 'ido-configure)
(require 'yasnippet-configure)
(require 'autocomplete-configure)
;(require 'elisphelp-configure)
(require 'common-configure)
;(require 'projectile-configure)
;(require 'helm-configure)
(require 'highlight-configure)
(require 'theme-configure)
;(require 'emacs-droid-configure)
;(require 'eproject-configure)
;(require 'redspace-configure)
(require 'magit-configure)
;(require 'textmate-configure)
;(require 'point-undo-configure)
;(require 'point-stack-configure)
;(require 'jdee-configure)
;(require 'w3m-configure)
;(require 'bookmark+-configure)
;(require 'icicles-configure)
;(require 'cedet-configure)
;(require 'ggtags-configure)


(provide 'configure)
